services:
  - type: web
    name: my-backend-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DB_HOST
        value: your-online-db-host.com
      - key: DB_USER
        value: your_user
      - key: DB_PASSWORD
        value: your_password
      - key: DB_NAME
        value: test1
